const Fr = {
  ChooseSys: 'Choisissez votre système',
  IntV: 'Intervilles',
  Cov: 'Covoiturage',
  Tav: 'Travailleurs',
  warnTextIntV: "Désolé, cette option n'est disponible que de :",
  Mn: 'Matin',
  Sr: 'Soir',
  whereFromTXT: 'Où allez vous ?',
  placeholderWhereG: 'Entrez votre lieu',
  NbPlace: 'Nombre de place disponible',
  Depart: 'Départ',
  Reserver: 'Réserver',
  Matricule: 'Matricule',
  destination: 'Destination',
  NoSmok:
    '- Je ne souhaite pas voyager avec des fumeurs - La ceinture est obligatoire ',
  Call_Number: 'Appeler le numéro',
  cancel: 'Annuler la',
  cancelTXT: 'Votre réservation à été annuléavec succès',
  CancelSsTXT:
    'Votre argent vous sera retourné avec un prélèvement de  8% du paiement',
  AssT: "Veuillez contacter le service  d'assistance",
  BackAccueil: "Retourner à l'accueil",
  NotDriver: 'Aucun voyage pour cette destination',
  MyWarn: 'Mes Alertes',
  CreateWarn: 'Créer une alerte',
  Ins: "Je m'inscris",
  LogTxt: "J'ai déjà un compte",
  Cra: 'Création de votre compte',
  NI: 'Veuillez remplir les champs suivant *',
  //Form
  Nm: 'Nom complet',
  EM: 'Email',
  MM: 'Mot de passe',
  DD: 'Date de naissance',
  RG: 'Région ',
  VV: 'Ville',
  IP: 'Informations personnelles *',
  ITP: 'Information très important',
  CT: "En continuant, je confirme que j'ai lu et accepté les conditions générales et la politique de confidentialité",
  next: 'SUIVANT',
  NmTT: 'Entrez votre numéro',
  NmTT2: 'Code de vérification',
  NmTT2H1: 'Entrez le code à 4 chiffres qui vous a été envoyé au',
  Mdf: 'Modifier',
  MTTT: 'Renvoyer le code dans',
  Ph: 'Photo',
  PC: 'Profil créé',
  DSP: 'Une photo de votre visage est requise afin que vos futures covoitureurs sache qui vous êtes !',
  CP: 'Choisir une photo',
  PP: 'Prendre une photo',
  PP1: 'Photo de profil',
  PE: 'Prochaine étape',
  PCs: 'Photo ajoutée à votre profil',
  SSTXT: '(Vous pourrez changer dans vos réglages comptes à tout moment)',
  SST: 'Dites-nous qui vous êtes :',
  C: 'Conducteur',
  P: 'Passagers',
  Same: 'Les deux',
  TP: 'Type de profil',
  SCP: 'Scanner mon permis',
  PTXT: 'Pour déposer une annonce et faire du covoiturage, nous devons vérifier votre permis de conduire.',
  PEV: 'Permis en cours de validation',
  TPV: 'Type de véhicule',
  TPVT: 'Pouvez-vous nous spécifier le type  de véhicule dont vous disposer ?',
  MRQ: 'Marque',
  MDRL: 'Modèle',
  DY: 'Année',
  MMTR: 'N° Matricule',
  TIS: 'Terminer mon inscription',
  good: 'BRAVO',
  start: 'COMMENCER',
  EEP: 'Effectuer le paiement,pour confirmer votre place',
  DDN: 'Débiter le numéro :',
  FDOP: 'Frais de transfert opérateur',
  MTOP: 'Montant total à payer',
  RRS: 'Votre réservation a été effectuée !',
  RAS: 'Je suis arrivé(e)',
  CPC: 'Choisissez votre formule '
};
export default Fr;
