const Drivers = [
  {
    id: 1,
    fisrtname: 'Pierre France',
    CourseState:'',
    State:true,
    lastname: 'Mr Beddy',
    photo: 'profil_Default1.png',
    tel: '055412890',
    available: false,
    date_of_departure: '14h22',
    destination: 'Bouake',
    current_location: 'Abobo',
    price: '1200XOF',
    car_details: {
      matricule: '129DMLCI',
      car_name: 'Toyotta',
      seatAvailable: 0,
      totalSeat: 5,
    },
  },
  {
    id: 2,
    fisrtname: 'Pierre Réné',
    CourseState:'close',
    State:false,
    lastname: 'Mr Freddy',
    photo: 'profil_Default2.png',
    tel: '055412890',
    available: false,
    date_of_departure: '14h22',
    destination: 'Man',
    current_location: 'Abobo',
    price: '1200XOF',
    car_details: {
      matricule: '129DMLCI',
      car_name: 'Toyotta',
      seatAvailable: 1,
      totalSeat: 5,
    },
  },
  {
    id: 3,
    fisrtname: 'Pierre Moi',
    CourseState:'end',
    State:false,
    lastname: 'Mr Lega',
    photo: 'profil_Default1.png',
    tel: '055412890',
    available: false,
    date_of_departure: '14h22',
    destination: 'Guiglo',
    current_location: 'Abobo',
    price: '1200XOF',
    car_details: {
      matricule: '129DMLCI',
      car_name: 'Toyotta',
      seatAvailable: 5,
      totalSeat: 5,
    },
  },
  {
    id: 4,
    fisrtname: 'Pierre DOPL',
    CourseState:'close',
    State:false,
    lastname: 'Mr MOUIll',
    photo: 'profil_Default2.png',
    tel: '055412890',
    available: false,
    date_of_departure: '14h22',
    destination: 'Azoper',
    current_location: 'Abobo',
    price: '700XOF',
    car_details: {
      matricule: '129DMLCI',
      car_name: 'Toyotta',
      seatAvailable: 4,
      totalSeat: 5,
    },
  },{
    id: 5,
    fisrtname: 'Pierre DOPL',
    CourseState:'close',
    State:false,
    lastname: 'Mr MOUIll',
    photo: 'profil_Default2.png',
    tel: '055412890',
    available: false,
    date_of_departure: '14h22',
    destination: 'Cocody',
    current_location: 'Abobo',
    price: '700XOF',
    car_details: {
      matricule: '129DMLCI',
      car_name: 'Toyotta',
      seatAvailable: 4,
      totalSeat: 5,
    },
  },{
    id: 5,
    fisrtname: 'Pierre DOPL',
    CourseState:'end',
    State:false,
    lastname: 'Mr MOUIll',
    photo: 'profil_Default2.png',
    tel: '055412890',
    available: false,
    date_of_departure: '14h22',
    destination: 'Faya',
    current_location: 'Abobo',
    price: '700XOF',
    car_details: {
      matricule: '129DMLCI',
      car_name: 'Toyotta',
      seatAvailable: 4,
      totalSeat: 5,
    },
  },{
    id: 6,
    fisrtname: 'Pierre DOPL',
    CourseState:'close',
    State:false,
    lastname: 'Mr MOUIll',
    photo: 'profil_Default2.png',
    tel: '055412890',
    available: false,
    date_of_departure: '14h22',
    destination: 'Bingerville',
    current_location: 'Abobo',
    price: '700XOF',
    car_details: {
      matricule: '129DMLCI',
      car_name: 'Toyotta',
      seatAvailable: 4,
      totalSeat: 5,
    },
  },
];
export default Drivers;
